feature-get-permission
fantastic-editor/FantasticEditorApi pull request #18
Opened 2024-05-23 12:42 UTC by DC-SY

### 🤔 这个变动的性质是？

- [x] ✨ 新特性开发
- [ ] 🐞 Bug 修复
- [ ] 🦢 重构
- [ ] 📝 文档、注释
- [ ] 🚀 打包、CI相关
- [ ] 🖐️ 测试用例
- [ ] 📘 其他改动（是关于什么的改动？）

### 💡 需求背景和解决方案

实现分页查询,模糊查询用户权限
  

### ⚠️ 是否是破坏性的改动？

- [ ] 是(yes)
- [x] 否(no)

2024-05-23 12:53 UTC, XiaoLFeng requested changes
代码修正后提交

2024-05-23 12:53 UTC, XiaoLFeng commented on src/main/kotlin/com/frontleaves/fantasticeditor/services/PermissionServiceImpl.java
> +        }
这一部分会忽略掉你的 search 内容，如果你的 page 和 size 不为空，而且你的搜索也不为空，那么最后你的 search1 = "" 是一个Blank 值

建议直接使用三段 if 形式直接执行。

![](https://i-cdn.akass.cn/2024/05/664f3c27983f4.png!wp)

2024-05-23 12:53 UTC, xiaolfeng commented on src/main/kotlin/com/frontleaves/fantasticeditor/services/interfaces/PermissionService.kt
> +}
Kotlin 规范审查 action 里面需要多回车保留最后一行，action 检查失败

2024-05-23 12:53 UTC, XiaoLFeng commented on src/main/kotlin/com/frontleaves/fantasticeditor/services/PermissionServiceImpl.java
> +        int size1 = 20;
属性值匹配，数据库传入参数要求为 Long，该部分内容统一字段长度

2024-05-23 12:53 UTC, XiaoLFeng commented on src/main/kotlin/com/frontleaves/fantasticeditor/controllers/v1/PermissionController.java
> +    @GetMapping("/list")
JavaDoc

2024-05-23 12:53 UTC, xiaolfeng commented on src/main/kotlin/com/frontleaves/fantasticeditor/controllers/v1/PermissionController.java
> +            @RequestParam(value = "size", defaultValue = "20") final Integer size) {
若前端错误传递非数字内容报错，返回 aborted; 检查内容不通过

2024-05-25 13:08 UTC, XiaoLFeng commented
尽快补完

2024-05-26 06:39 UTC, DC-SY commented on src/main/kotlin/com/frontleaves/fantasticeditor/controllers/v1/PermissionController.java
> +            @RequestParam(value = "size", defaultValue = "20") final Integer size) {
没有理解,aborted是什么
我使用了@Min(1)注解,如果传入参数小于1或者不是一个数字,则抛出MethodArgumentNotValidException异常,这样ok吗?

2024-05-26 06:41 UTC, XiaoLFeng commented on src/main/kotlin/com/frontleaves/fantasticeditor/controllers/v1/PermissionController.java
> +            @RequestParam(value = "size", defaultValue = "20") final Integer size) {
apifox 执行时，若前端输入非数字内容会直接终止连接，不是返回报错。 Integer 改为 String 后在 controller 进行检查

2024-05-26 06:54 UTC, XiaoLFeng approved these changes
注意代码规范样式，以及前端传入数据属于不可信数据，注意检查传入

2024-05-26 06:55 UTC, merged